### ISSUE TITLE
Is it possible to use Swarm as change tracker in CoreData?

### ISSUE THREAD

**Issue by shalom-aviv** [prisma-ai/Sworm#10]
Hi 

Is it possible to use Swarm as change tracker in CoreData?
If not
Could you give advise how implement this functionality in cooperation with Sworm?

Thank you

**Comment by geor-kasapidi** [comment]
Hi! Please, look at this demo:

[demo_sworm.zip](https://github.com/prisma-ai/Sworm/files/8650024/demo_sworm.zip)

**Comment by shalom-aviv** [comment]
Thanks!

Yeee i thought about this approach.
But I'm looking more flexible solution. 

I will message you, in case when create something interesting ;)

**Comment by geor-kasapidi** [comment]
🤝
