### ISSUE TITLE
CoreData: warning: Unable to load class named '' for entity 'Entity'.  Class not found, using default NSManagedObject instead.

### ISSUE THREAD

**Issue by jidaojiuyou** [prisma-ai/Sworm#12]
CoreData: warning: Unable to load class named '' for entity 'Entity'.  Class not found, using default NSManagedObject instead.

How to resolve this warning?

Ipad mini 6(Ios 16.3)
Mac Air 2020 M1 (MAC OS 13.3)
XCode 14.2(14C18)

**Comment by geor-kasapidi** [comment]
Hello! please ignore these warnings - this is an internal log inside the CoreData framework and does not affect any functionality.
