### ISSUE TITLE
delete operation throws build error

### ISSUE THREAD

**Issue by ghost** [prisma-ai/Sworm#2]
I created a generic repository that gets a `PersistentContainer` injected (I followed you instructions up to there):

```
public class BaseRepository<T>: Repository where T: ManagedObjectConvertible {
	
	public var persistentContainer: PersistentContainer
	
	init(persistentContainer: PersistentContainer) {
		
		self.persistentContainer = persistentContainer
	}
	
	public func allItems() throws -> [T] {

		try self.persistentContainer.perform { context in
			
			try context.fetch(T.all).map { try $0.decode() }
		}
	}
	
	public func create(_ item: T) throws {
		try self.persistentContainer.perform { context in
			
			try context.insert(item)
		}
	}
	
	public func remove(_ item: T) throws {
		try self.persistentContainer.perform { context in
			
			try context.delete(item)
		}
	}
} 
```

However, the "remove" function where the `delete` operation on the context is used, throws a build error:

```
Cannot convert value of type 'T' to expected argument type 'ManagedObject<PlainObject>'
```

I tried around, but I cannot figure out how to fix this. Do you have any ideas? 

The calling part looks like this (a repository factory):

```
	public func makeRepository<R>(for storyType: StoreType) -> R where R: Repository {

		switch storyType {
			case .country:
				return BaseRepository<Country>(persistentContainer: persistentContainer) as! R
				
			case .location:
				return BaseRepository<Location>(persistentContainer: persistentContainer) as! R
		}
	}
```

where 

```
public protocol Repository {
	associatedtype T: ManagedObjectConvertible
	
	var persistentContainer: PersistentContainer { get }
	
	func allItems() throws -> [T]
}
```

Thanks for your support!

**Comment by geor-kasapidi** [comment]
Hi @innoreq! Let me explain. You need to call something like this:

``` swift
	public func remove(_ item: T) throws {
		try self.persistentContainer.perform { context in
                        try context.delete(T.all.where(\T.id == item.id))
		}
	}
```

*delete* method where argument is ManagedObject<T> typically uses when you first fetch some objects from db:

``` swift
	public func remove(_ item: T) throws {
		try self.persistentContainer.perform { context in
                        let objects = try ctx.fetch(T.all.where(\T.id == item.id))
                        try objects.forEach { try context.delete($0)  }
		}
	}
```

**Comment by ghost** [comment]
Thanks for your explanation. Makes things much clearer to me.

I now changed the repo this way (according to suggestion #1):

```
	public func remove(_ item: T) throws {
		try self.persistentContainer.perform { context in

			guard let uuid = item.uuid else { return }
			
			try context.delete(request: T.all.where(\T.uuid == uuid))
		}
```

I'm calling that from a test:

```
	func testStore() throws {
		
		let store = Store(type: .inMemory,
						  seeder: nil)
		
		let repo: BaseRepository<Country> = store.makeRepository(for: .country)

		let allBefore = try repo.allItems()
		XCTAssertEqual(allBefore.count, 0)
		
		let new: Country = .init()
		try repo.create(new)
		
		let allAfter = try repo.allItems()
		XCTAssertEqual(allAfter.count, 1)
		XCTAssertEqual(allAfter[0], new)
		
		try repo.remove(new)
		
		let allRemaining = try repo.allItems()
		XCTAssertEqual(allRemaining.count, 0)
	}
```

This fails with a fatal:
```
Thread 1: Fatal error: unsafelyUnwrapped of nil optional
```

that happens here:

```
extension ManagedObjectConvertible {
    static func attribute(_ keyPath: PartialKeyPath<Self>) -> Attribute<Self> {
        self.attributes.first(where: { $0.keyPath == keyPath }).unsafelyUnwrapped
    }
...
```

because self.attributes.first() returns `nil` which obviously cannot be `unsafelyUnwrapped`.

Am I still doing something wrong? The `uuid` attribute is optional for the CoreData NSManagedObject, as well as for the domain item; but even it is not for the domain item, the error persists.

EDIT:
When explaining things, you always see things you did not see until then... I noticed that the "new" item was created with a plain `init()`. I thought that possible this was the reason, as it should be initialized with proper values. So, I changed that to #2 

```
		let new: Country = .init(uuid: .init(), name: "")
```

and hoped for some change - but the fatal still appears...

**Comment by geor-kasapidi** [comment]
Your code is correct. This error appears when keyPath is missing in attribute list (ManagedObjectConvertible conformance) - https://github.com/prisma-ai/Sworm/blob/main/docs/basic_usage.md

please, check your implementation.

**Comment by ghost** [comment]
Hm, checked it, but it seems to be as required - or do I miss something:

```
public struct Country: Codable, Equatable, IdentifiedItem {
	
	public var uuid: UUID?
	public var name: String
}

extension Country: ManagedObjectConvertible {
	
	public init() {
		self.uuid = .init()
		self.name = .init()
	}

	public static let entityName = "Country"
	
	public static let attributes: Set<Attribute<Country>> = [
		
		.init(\.uuid, "uuid"),
		.init(\.name, "name"),
	]
	
	public struct Relations {
		let locations = ToManyRelation<Location>("locations")
	}
	
	public static let relations = Relations()
}
```

**Comment by geor-kasapidi** [comment]
oh, i see - give me some time to investigate the problem, i will return to you soon

**Comment by ghost** [comment]
Great, thank you!

**Comment by geor-kasapidi** [comment]
@innoreq please, look at https://github.com/prisma-ai/Sworm/pull/3

i'v realised that indirect keypath usage (via some protocol) doesn't work due to tricky swift runtime, so i suggest you solution implemented in pull request #3 ☝🏻

**Comment by ghost** [comment]
Well, looks good. Changed my code according to the changes in the pull request, and everything's working fine!
Thanks a lot for your support!

**Comment by geor-kasapidi** [comment]
You are welcome 🤝
