### ISSUE TITLE
Q: How to update an existing item?

### ISSUE THREAD

**Issue by ghost** [prisma-ai/Sworm#4]
Just for better understanding: There is no "update" method in Sworm, just insert and delete. How is an existing object updated? 

My use case is an editor sheet, that provides "cancel" and "save" operations. This includes (a) the need for a rollback, and (b) the need for an update.

The missing "update" operation may be interpreted in a way that Sworm updates "on-the-fly" whenever an attribute changes.

So, how does Sworm work in this context? How should an update intentionally be handled?

**Comment by geor-kasapidi** [comment]
Hi again, @innoreq ! It's pretty easy: you need to manage your pure swift object inside editor sheet, update properties, just do regular staff. When it's time to save or rollback, just do nothing in case of "rollback" (swift object will be deallocated), otherwise (save), execute next code (i assume you continue use repo pattern):

``` swift
    func update(item: T) throws {
        try self.pc.perform { context in
            if let object = try context.fetchOne(T.all.where(T.idKeyPath == item[keyPath: T.idKeyPath])) {
                object.encode(item)
            }
        }
    }
```

**Comment by geor-kasapidi** [comment]
look at #6

**Comment by ghost** [comment]
Things are pretty easy sometimes. I like it.

Just added a "creation" branch to the `if` statement - this way, the item is created, if not yet available in the store.

```
public func update(_ item: T) throws {
		try self.persistentContainer.perform { context in

			if let object = try context.fetchOne(T.all.where(T.idKeyPath == item[keyPath: T.idKeyPath])) {
				object.encode(item)
			} else {
				try context.insert(item)
			}
		}
	}
```
