### ISSUE TITLE
Is it possible to sort items by several fields?

### ISSUE THREAD

**Issue by shalom-aviv** [prisma-ai/Sworm#7]
For example entity has priority and createDate field
Firstly I should sort by priority and after by createDate

**Comment by geor-kasapidi** [comment]
Hi, @shalom-aviv! Just [updated](https://github.com/prisma-ai/Sworm/commit/8d2852e4919fd3e57e1c9e26a7fb033d1001b00b) the docs.

**Comment by shalom-aviv** [comment]
Awesome
Thanks
