### ISSUE TITLE
Cold you please add sample for "read / write data models or attributes separately."

### ISSUE THREAD

**Issue by shalom-aviv** [prisma-ai/Sworm#8]
```
.... 
In addition to accessing graphics, ManagedObject has a set of paired `encode` / `decode` methods 
that allow you to read / write data models or attributes separately.
```

from  [here](https://github.com/prisma-ai/Sworm/blob/5314f0409a28f05de4602fedd5fed82c5187cdaf/docs/read_write.md)

**Comment by geor-kasapidi** [comment]
Hi, @shalom-aviv! Just [updated](https://github.com/prisma-ai/Sworm/commit/8d2852e4919fd3e57e1c9e26a7fb033d1001b00b) the docs.

**Comment by shalom-aviv** [comment]
Awesome
Thanks
