### ISSUE TITLE
Relations cannot be set

### ISSUE THREAD

**Issue by ghost** [prisma-ai/Sworm#9]
Hello again,

I'm struggling with relations and their handling. The use case is:

* There are companies, that have a many-to-many-relationship with persons
* I create a company, and I create some persons.
* I want to assign the persons to the company.

Actually, pretty simple.

The test case is:

```
		let domainStore: DomainStore = .init(kind: .temporary)

		let companyStore = GenericAPI<Company>(domainStore: domainStore)
		let personStore = GenericAPI<Person>(domainStore: domainStore)
		
		companyStore.refresh()
		personStore.refresh()
		
		XCTAssertEqual(companyStore.list, [])
		XCTAssertEqual(personStore.list, [])

		// Add some persons.
		var new1: Person = personStore.add()
		new1.name = "Paul"
		personStore.save(new1)
		
		var new2: Person = personStore.add()
		new2.name = "Peter"
		personStore.save(new2)
		
		XCTAssertEqual(personStore.list.count, 2)
		
		// Add a company.
		var new3: Company = companyStore.add()
		new3.name = "The AG"
		companyStore.save(new3)
				
		XCTAssertEqual(companyStore.list.count, 1)
		XCTAssertEqual(companyStore.list[0].name, "The AG")
		
		new3.persons = [new1, new2]
```
The error occurts in the last line, where the compiler says: "Value of type `Company` has no member `persons`."

Now, Company is defined such:

```
public struct Company: DomainType {
	
	public init(uuid: UUID, name: String) {
		self.uuid = uuid
		self.name = name
	}
	
	public var uuid: UUID
	public var name: String
}

extension Company {
	
	public static var idKeyPath: KeyPath<Company, UUID> {
		\.uuid
	}
	
	public init() {
		self.uuid = .init()
		self.name = .init()
	}
	
	public static let entityName = "CompanyMO"
	
	public static let attributes: Set<Attribute<Company>> = [
		
		.init(\.uuid, "uuid"),
		.init(\.name, "name"),
	]
	
	public struct Relations {
		public init() {}
		public let persons = ToManyRelation<Person>("persons")
	}
	
	public static let relations = Relations()
}

```

So, actually everything as stated in your directions and test cases, where a `Book` has `authors`.

The `public init()` was kind of desperation task, cause I thought it may be a visiblity problem (the domain types are defined in a package), but it did not change anything.

So it seems I'm doing something wrong - but what?

Thanks in advance for your help!

**Comment by geor-kasapidi** [comment]
Hi, @innoreq ! Relations can be achieved on ManagedObject<T> instance inside **perform** closure. Look at the [example](https://github.com/prisma-ai/Sworm/blob/bcffae71a0c361ae747cc0c1c65637dc6fe9af44/Tests/SwormTests/ReadWriteTests.swift#L43-L46).

**Comment by geor-kasapidi** [comment]
Please, read the [docs](https://github.com/prisma-ai/Sworm/blob/main/docs/read_write.md) - there is an example of reading/writing relations.

**Comment by ghost** [comment]
Ok, so the relations are not part of the domain types (i.e., Company), but _only_ part of the storage types (i.e., CompanyMO), right?

**Comment by geor-kasapidi** [comment]
exactly!
